### ISSUE TITLE
Wizard's hitbox allows you to float on ledges

### ISSUE THREAD

**Issue by MattsAttack** [PHS-TSA/wizards-in-calculus#20] opened 2024-02-02 03:28 UTC
### Contact Details

@MattsAttack

### What happened?

Basically, since the wizard's hand and hat sticks out, he can get stuck and it will keep you from falling.

### Reproduction steps

1. Try to jump on/off ledge

### What should have happened?

You should have fallen!

### Date

2024-02-01

### OS

Windows

### Context

![image](https://github.com/PHS-TSA/Wizzas-In-Calculus/assets/71449347/3a2bb6af-c167-4f04-b4e2-c4a65cc38aa3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

_**CC:** @lishaduck_

**Comment by lishaduck** [comment] 2024-02-02 03:29
Duplicate of #19.

**Comment by lishaduck** [comment] 2024-02-02 03:42
Nope. Following some investigation, I believe that this is a separate issue. I'll try to fix it tomorrow.

**Comment by lishaduck** [comment] 2024-02-02 04:25
I can't decide if this is awesome or terrible. It feels wrong, but it's also a free "hang on when knocked off" mechanic.

**Comment by iiAzui** [comment] 2024-02-03 12:31
we removed it, (it was because eli's hitbox lol

**Comment by iiAzui** [comment] 2024-02-03 12:32
we should just have the square hitbox

**Closed as completed** 2024-02-03 20:03 UTC
Labels: bug
